#!/usr/bin/env node

/**
 * Copyright ©2022 Dana Basken
 */

const argv = require("minimist")(process.argv.slice(2));
const Ignis = require("./src/Ignis");

(async () => {
  const ignis = new Ignis(argv);
  await ignis.start();
})();
